import Header2 from "@/components/Header2";
import Header1 from "../components/Header1";
import Header3 from "@/components/Header3";
import Image from "next/image";
import Head from "next/head";
import Header4 from "@/components/Header4";
import Footer from "@/components/Footer";

const Home = () => {
  return (
    <div>
      <Head>
        <title>OYO : Indias's Largest Online Hotel Booking Platform .</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Header1 />
      <Header2 />
      <Header3 />
      <div className="mx-20">
        <div className=" my-14 mb-14">
          <Image
            src={"/banner1.avif"}
            alt="banner"
            width={200}
            height={200}
            className="w-full h-80"
          />
        </div>
        <div className="">
          <Image
            src={"/banner2.avif"}
            alt="banner"
            width={200}
            height={200}
            className="w-full h-40"
          />
        </div>
        <Header4 />
      </div>
      <Footer />
    </div>
  );
};

export default Home;
